PROJECT_SCHEME = 'MY_PROJECT_SCHEME' # Your Project scheme for building ex MyApp
PROJECT_NAME = 'MYAPP.xcodeproj' # Your Project file name ex. MyApp.xcodeproj
WORKSPACE_NAME = 'MYWORKSPACE.xcworkspace' # Your workspace file name ex. MyApp.xcworkspace
CONFIGURATION = 'Release' # The build configuration to use
INFOPLIST_PATH = 'FOO/MYPROJECT-Info.plist' # Your info plist file path
API_TOKEN = 'MY_API_TOKEN' # Your TestFlight API Token
TEAM_TOKEN = 'MY_API_TOKEN' # Your TestFlight Team Token
RELEASE_LIST = 'Internal - Always Release' # TestFlight list of people you want to notify for release

desc 'Build IPA'
task :buildipa do
  puts "Attempting to build IPA..."
  sh "rm -rf *.ipa"
  sh "rm -rf *.app.dSYM.zip"
  sh "ipa build --scheme #{PROJECT_SCHEME} --workspace #{WORKSPACE_NAME} --project #{PROJECT_NAME} --configuration #{CONFIGURATION} --clean /tmp"
end

desc "Rev the build numbers in a project's plist"
task :rev do
  puts "Attempting to update #{INFOPLIST_PATH} build version..."
  oldVersion = `/usr/libexec/PlistBuddy -c "Print CFBundleVersion" #{INFOPLIST_PATH}`
  puts "The old version: #{oldVersion}"

  newVersion = Integer(oldVersion) + 1
  `/usr/libexec/PlistBuddy -c "Set :CFBundleVersion #{newVersion}" #{INFOPLIST_PATH}`
  puts "The new version: #{newVersion}"
end

desc "Commit git changes"
task :push do
  version = `/usr/libexec/PlistBuddy -c "Print CFBundleVersion" #{INFOPLIST_PATH}`
  sh "git add #{INFOPLIST_PATH}"
  sh "git commit -m 'Release #{version}'"
  sh "git tag -a b#{version}"
  sh "git push origin master --tags"
end

desc 'Deploy Release Build to TestFlight'
task :release => ['rev','buildipa'] do
  puts "Attempting to release build to TestFlight..."
  puts "Release notes for release:"
  puts release_notes
  sh "ipa distribute:testflight --api_token #{API_TOKEN} --team_token #{TEAM_TOKEN} --lists #{RELEASE_LIST} --notify --notes '#{release_notes}' "
  Rake::Task["push"].execute
end

def release_notes
  begin
    IO.read('RELEASE_NOTES.md')
  rescue
    'Add RELEASE_NOTES.md at project root to post release notes.'
  end
end
