file = File.open('build_settings')
contents = file.read
@settings = eval(contents)

desc 'Build IPA'
task :buildipa do
  puts "Attempting to build IPA..."
  sh "rm -rf *.ipa"
  sh "rm -rf *.app.dSYM.zip"
  sh "ipa build --scheme #{@settings[:scheme]} --workspace #{@settings[:workspace]} --project #{@settings[:project]} --configuration #{@settings[:configuration]} --clean /tmp"
end

desc "Rev the build numbers in a project's plist"
task :rev do
  puts "Attempting to update #{@settings[:info_plist]} build version..."
  oldVersion = `/usr/libexec/PlistBuddy -c "Print CFBundleVersion" #{@settings[:info_plist]}`.chomp
  puts "The old version: #{oldVersion}"

  newVersion = Integer(oldVersion) + 1
  `/usr/libexec/PlistBuddy -c "Set :CFBundleVersion #{newVersion}" #{@settings[:info_plist]}`
  puts "The new version: #{newVersion}"
end

desc "Commit git changes"
task :push do
  version = `/usr/libexec/PlistBuddy -c "Print CFBundleVersion" #{@settings[:info_plist]}`.chomp
  sh "git add #{@settings[:info_plist]}"
  sh "git commit -m 'Release #{version}'"
  sh "git tag -a b#{version} -m 'Tag #{version}'"
  sh "git push origin master --tags"
end

desc "Generates HTML documentation using appledoc"
task :docs do
  system <<-EOS
    appledoc \\
      --project-name #{@settings[:app_name]} \\
      --project-company #{@settings[:company]} \\
      --company-id #{@settings[:company_id]} \\
      --output docs \\
      --create-html \\
      --no-create-docset \\
      --ignore Pods \\
      --keep-intermediate-files .
  EOS
end

desc 'Deploy Release Build to TestFlight'
task :release => ['rev','buildipa'] do
  puts "Attempting to release build to TestFlight..."
  sh "ipa distribute:testflight --api_token #{@settings[:api_token]} --team_token #{@settings[:team_token]} --lists #{@settings[:release_list]} --notify --notes '#{@settings[:release_notes]}' "
  Rake::Task["push"].execute
end
